#!/bin/bash

apk add --no-cache squid squid-lang-zh nghttp2 supervisor py2-pip ca-certificates
pip install pyrad hurry.filesize

wget -O- https://github.com/jiehanzheng/squid2radius/archive/14e23cbdf9d4a95a32b7ae3e53e1efe4823d34fd.tar.gz | tar -C /opt -xzf -
cd /opt
mv squid2radius-* squid2radius
