#!/bin/bash

cd /opt/squid2radius
python3 squid2radius.py /var/log/squid/access.log {{RADIUS_SERVER}} {{RADIUS_SECRET}}
cd /var/log/squid/
if [[ -f access.log.23 ]]; then
    seq 23 -1 0 | xargs -I {} cat access.log.{} > archive_access.log
    rm access.log.*
    savelog -c {{LOG_NUM}} archive_access.log
fi
