#!/bin/bash

set -x
set -e

build_nghttp2(){
    apk add openssl libgcc libstdc++ jemalloc libev
    apk add --virtual build-deps openssl-dev gcc g++ git jemalloc-dev libev-dev autoconf automake make libtool
    NGHTTP2_SRC=/usr/local/src/nghttp2
    git clone --branch=$NGHTTP2_VERSION --depth=1 https://github.com/nghttp2/nghttp2.git $NGHTTP2_SRC
    cd $NGHTTP2_SRC
    autoreconf -i 
    automake
    autoconf
    ./configure
    make -j `getconf _NPROCESSORS_ONLN`
    make install-strip

    cd /
    rm -rf $NGHTTP2_SRC
}
build_squid2radius(){
    apk add py-pip ca-certificates openssl
    pip install pyrad hurry.filesize
    cd /opt
    wget -O- https://github.com/billzhong/squidlog/archive/f1dcaef70eb2aa21253682b1d9c754da784e473b.tar.gz | tar -xzf -
    mv squidlog-* squid2radius
}

build_telegraf(){
    apk add --virtual build-deps build-base go git
    export GOPATH=/go
    go get github.com/influxdata/telegraf
    cd $GOPATH/src/github.com/influxdata/telegraf
    git checkout $TELEGRAF_VERSION
    make
    install -m755 $GOPATH/bin/telegraf /usr/bin/
}

apk update
apk add squid squid-lang-zh supervisor tzdata
build_telegraf
build_squid2radius
build_nghttp2
mkdir -p \
    /var/log/supervisor \
    /var/log/nghttpx \
    /var/log/squid

apk del --purge build-deps
rm -rf /var/cache/apk/*
rm /etc/logrotate.d/squid
